### ISSUE TITLE
404 error for link

### ISSUE THREAD

**Issue by lpantano** [charite/Q#1]
Hi!
congrats for the tool!!!!
I was trying to look information how to use it, but cannot find it inside github.
I tried to go to http://compbio.charite.de/Q/, but gives me 404 error.

It would be great some quick start here! willing to test it.

**Comment by visze** [comment]
Dear Lorena,

have a look at http://charite.github.io/Q/

Best regards,
Max

**Comment by lpantano** [comment]
so nice, thanks!
