### ISSUE TITLE
Adapter file format?

### ISSUE THREAD

**Issue by ChiWPak** [charite/Q#10]
Hi:

Following the Q nexus manual, I created an adapter file, `adapters.fa`, which looks like

>adapter1
AGATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
>adapter2
GATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
>adapter3
ATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
>adapter4

However, when I try to use this adapter file with flexcat, I get the following message:

End for adapter "adapter1" not specified, adapter will be ignored.
End for adapter "adapter2" not specified, adapter will be ignored.
End for adapter "adapter3" not specified, adapter will be ignored.
End for adapter "adapter4" not specified, adapter will be ignored.

I'm not understanding what format flexcat is expecting for the adapter file. Any feedback is very appreciated!

**Comment by catkira** [comment]
There is an example adapters.fa file in the Q/data folder.
It should look like this:

 >adapter1:3':
AGATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
 >adapter2:3':
GATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
 >adapter3:3':
ATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
 >adapter4:3':
TCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC
 >adapter5:3':
CGGAAGAGCACACGTCTGGATCCACGACGCTCTTCC

Am 03.11.2017 um 15:26 schrieb Chi W Pak:

**Comment by ChiWPak** [comment]
Thanks for the reply. Sorry I didn't think to look through the other folders. Appreciate the help!
