### ISSUE TITLE
"Trying to open BAM file and ZLIB is not available!"

### ISSUE THREAD

**Issue by PanosFirmpas** [charite/Q#2]
Hi,
We've tried installing and running "Q" in two different Ubuntu systems,
and in both cases configure/make/makeinstall runs smoothly
but then when we try to run it with "-t afile.bam" and "-o somefolder" , we get the following error:

"
ERROR: Trying to open BAM file and ZLIB is not available!
ERROR: Could not open <MY_FILE_NAME>.bam !
ERROR: Function 'ReadAlignmentFile' failed !"
"

It looks like a problem with seqan but I don't know what I could do to fix it, any ideas?

**Comment by hansenp** [comment]
Try

sudo apt-get install zlib1g-dev libbz2-dev libboost-dev libgomp1

and recompile Q. Alternatively, use the precompiled linux binary for Q which can be downloaded from here

http://charite.github.io/Q/downloads/executables/Linux_x86_64_binary/Q-1.0.0/Q

Best,
Peter
