### ISSUE TITLE
boost files missing

### ISSUE THREAD

**Issue by frenkiboy** [charite/Q#3]
The readme file says that all of the boost dependencies are found in src/boost, but the folder
seems to be missing.

Could you please just tell which files are necessary?

Cheers!

Vedran Franke

**Comment by frenkiboy** [comment]
Sorry, I've only been reading the README file. Found the compiled binary on the site.

**Comment by MosheOlshansky** [comment]
Hi,

Can you please tell me where I can find the compiled binary for CentOS?

Thank you.

**Comment by MosheOlshansky** [comment]
Found it and it works.

**Comment by hansenp** [comment]
Initially, we tried to keep the number of dependencies as small as possible. But then we thought that boost is not hard to get and that our code should be adapted to new versions of boost to keep our code more up-to-date. As mentioned above there is a statically pre-compiled binary for Linux (now also in the repository) which does not need any runtime libraries and therefore should run without further ado.
