### ISSUE TITLE
Compiles but report Error "ERROR: Trying to open BAM file and ZLIB is not available!"

### ISSUE THREAD

**Issue by xubeisi** [charite/Q#4]
First didn't complies, then installed libbz2. There is lib/libbz2.a and include/bzlib.h under /home/user/opt/libbz2/

./configure --prefix=/home/user/opt/Q-2015-v1 --libdir=/home/user/opt/libbz2/lib

then replace

LIBS = -lgomp -lbz2

with

LIBS = -lgomp -lbz2  -L/home/user/opt/libbz2/lib

make
make install

both complies

But 

/home/user/opt/Q-2015-v1/Q --treatment-sample T.bam --control-sample INPUT.bam --out-prefix test -pc 6

will report

ERROR: Trying to open BAM file and ZLIB is not available!
ERROR: Could not open T.bam !
ERROR: Function 'ReadAlignmentFile' failed !

tried 

make CFLAGS=-DSEQAN_HAS_ZLIB=1

or 

add
# ifndef SEQAN_HAS_ZLIB
# define SEQAN_HAS_ZLIB 1
# endif

to

src/seqan/core/include/seqan/stream.h

both complied success but reported same error

I seems have zlib that there are 

libz.a  libz.so  libz.so.1  libz.so.1.2.5

under /home/user/opt/zlib-1.2.5/lib and /home/user/opt/zlib-1.2.5/lib is in my $LD_LIBRARY_PATH

Anything else I can try?

Thanks!

**Comment by xubeisi** [comment]
cat /etc/redhat-release
CentOS release 6.1 (Final)

g++ --version
g++ (GCC) 4.8.1

source files from "git clone https://github.com/charite/Q"

**Comment by hansenp** [comment]
You could use statically pre-compiled binaries from here:

http://charite.github.io/Q/downloads/executables/Linux_x86_64_binary/Q-1.0.0/Q

**Comment by hansenp** [comment]
Sorry for the late response. I fixed the problem in 'src/Makefile.am'.

**Comment by xubeisi** [comment]
Thanks! In a preliminary test in mouse mm9
peaks called by Q didn't very consistent to MACS2, particular for broad markers(or mixed marker like PolII). In this test, I didn't used broad peak model of MACS2, but MACS2 should work for H3K4me1 though.

![image](https://cloud.githubusercontent.com/assets/1790841/9967381/ef3bfb28-5e07-11e5-9ba5-16bd02a8e9a1.png)

I didn't find broad peak parameter from Q. Wondering will Q optimize for broad peak in the future?
