### ISSUE TITLE
Corrupt memory

### ISSUE THREAD

**Issue by davek44** [charite/Q#6]
Though I can successfully execute Q on the BAM file suggested in the Tutorial (http://charite.github.io/Q/tutorial.html), the program crashes on my own BAM file. I'm on CentOS.

```
(DK)[dkelley@dkelley01 data]$ Q -p 4 -t foxa2_hepg2.bam -wbt -o foxa2_hepg2
*** glibc detected *** Q: double free or corruption (!prev): 0x000000000e2e4080 ***
======= Backtrace: =========  
[0x4f83b2]
[0x4fae4f]
[0x431a02]
[0x424948]
[0x4ce0db]
[0x400449]
======= Memory map: ========  
00400000-005c5000 r-xp 00000000 00:18 10795374991                        /n/home03/dkelley/bin/Q
007c4000-007c7000 rw-p 001c4000 00:18 10795374991                        /n/home03/dkelley/bin/Q
007c7000-007e3000 rw-p 00000000 00:00 0
019c9000-13753000 rw-p 00000000 00:00 0                                  [heap]
2adc35494000-2adc36495000 rw-p 00000000 00:00 0
2adc36495000-2adc36496000 ---p 00000000 00:00 0
2adc36496000-2adc36696000 rw-p 00000000 00:00 0
2adc36696000-2adc36697000 ---p 00000000 00:00 0
2adc36697000-2adc36897000 rw-p 00000000 00:00 0
2adc36897000-2adc36898000 ---p 00000000 00:00 0
2adc36898000-2adc36a98000 rw-p 00000000 00:00 0
2adc37496000-2adc39497000 rw-p 00000000 00:00 0
2adc3c000000-2adc3c10e000 rw-p 00000000 00:00 0
2adc3c10e000-2adc40000000 ---p 00000000 00:00 0
2adc44000000-2adc4411f000 rw-p 00000000 00:00 0
2adc4411f000-2adc48000000 ---p 00000000 00:00 0
2adc4c000000-2adc4f14d000 rw-p 00000000 00:00 0
2adc4f14d000-2adc50000000 ---p 00000000 00:00 0
2adc50000000-2adc55002000 rw-p 00000000 00:00 0
7fffcbc39000-7fffcbc52000 rw-p 00000000 00:00 0                          [stack]
7fffcbe00000-7fffcbe01000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
```

The BAM file was obtained using the following command.

```
bowtie2 -U ENCFF000PIT.fastq.gz -x bowtie2/hg19 | samtools view -q 3 -bS - | samtools sort -T foxa2_hepg2_sort -O bam -o foxa2_hepg2.bam -
```

I'd be happy to send the BAM file if that would help. Thanks for any help you can provide!

**Comment by hansenp** [comment]
Yes, the BAM file might be helpful.

Are you using the precompiled binaries of Q or did you compile from source?

**Comment by davek44** [comment]
I've tried both, and I get the same result. Thanks for taking a look.

Here's the file: https://www.dropbox.com/s/2xv6tq2qb6rxggr/foxa2_hepg2.bam?dl=0

**Comment by mcieslik-mctp** [comment]
I am seeing similar errors on all inhouse files I try (paired-end, aligned using STAR). I tried both the precompiled and 1.1.0 self-compiled from github.
**\* Error in `Q': free(): invalid next size (normal): 0x0000000002f668b0 ***

**Comment by hansenp** [comment]
The first error (davek44) seems to be a minor bug in the option for writing bedgraph files (-wbt). I will try fix it tomorrow.

The second error (mcieslik-mctp) seems to be something related to paired end data. There is also a pre-compiled binary for 1.1.0 in Q/bin. Are you using this?

If so, it would be helpful if you could provide me with a BAM file and the command line you are using.

**Comment by hansenp** [comment]
Fixed the bug reported by davek44 in function writeBedGraph.

**Comment by davek44** [comment]
Works now for me. Thanks!
